### ISSUE TITLE
Size of icon files to big

### ISSUE THREAD

**Issue by harborsiem** [HerbertLausmann/HL.IconPro#1]
Mainly if one have a png Image inside the Icon-file (Frame 256 x 256), the stored Icon-file is to big. The stored Icon-file is not wrong, but only to big.
I was looking at source code and I think I have an idea to fix this.
In HL.IconPro.Lib.Wpf there is an abstract class named "Codec". In this class is a method named "GetImageFrameBuffer". This method returns at two places a byte array with "return frameBuffer.GetBuffer();"
A better return maybe "return frameBuffer.ToArray();" at both places.
Method ToArray() will give you an Array with the length of the memorystream.
Method GetBuffer() will give you an Array with the capacity of the memorystream.

**Comment by HerbertLausmann** [comment]
Hi!

I'm taking on your suggestion. Thanks.
But seems like it made no change in the final file size:

![image](https://github.com/HerbertLausmann/HL.IconPro/assets/6272941/efb0346a-22b8-4a44-a55b-91107a4091f6)
